# Задание на повторение материала

In [1]:
import numpy as np

### 1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [16]:
a=np.linspace(12,24,12,dtype=np.int64)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24], dtype=int64)

### 2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [57]:
a1=a.reshape(1,12)
a1

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24]], dtype=int64)

In [58]:
a2=a.reshape(12,1)
a2

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [24]], dtype=int64)

In [42]:
a3=a.reshape(2,6)
a3

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 24]], dtype=int64)

In [41]:
a4=a.reshape(6,2)
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 24]], dtype=int64)

In [54]:
a5=a.reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 24]], dtype=int64)

### 3.Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).


In [59]:
a1=a.reshape(-1,12)
a1

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24]], dtype=int64)

In [60]:
a2=a.reshape(12,-1)
a2

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [24]], dtype=int64)

In [61]:
a3=a.reshape(-1,6)
a3

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 24]], dtype=int64)

In [62]:
a4=a.reshape(-1,2)
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 24]], dtype=int64)

In [63]:
a5=a.reshape(-1,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 24]], dtype=int64)

### 4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

#### a2 - массив 1 столбец, 12 строк

In [76]:
a2.shape

(12, 1)

#### Для одномерного массива характерно  a2[0]=значение

In [77]:
a2[1]

array([13], dtype=int64)

In [78]:
a2[1][0]

13

#### a2[1][0]=13 массив двумерный.

### массив Numpy, состоящий из одного столбца и 12 строк - двумерный

### 5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [116]:
a = np.random.randn(3, 4)
a

array([[-0.17800475,  0.70488213, -1.68759556, -0.11350585],
       [-0.92657961,  0.04276332, -0.90213636,  0.29500686],
       [-0.1146152 , -0.97345623,  0.18063499,  0.22246351]])

In [117]:
a1=a.flatten()
a1

array([-0.17800475,  0.70488213, -1.68759556, -0.11350585, -0.92657961,
        0.04276332, -0.90213636,  0.29500686, -0.1146152 , -0.97345623,
        0.18063499,  0.22246351])

In [118]:
a1.size==a.size

True

### 6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [119]:
a=np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

### 7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [135]:
b=np.arange(20,1,-2)
b=b.reshape(-1,10)

In [128]:
a.shape

(10,)

In [137]:
b.shape

(1, 10)

#### a- одномерный, b двумерный массив

### 8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.


In [167]:
a=np.zeros((3,2))
a.size,a

(array([[0., 0.],
        [0., 0.],
        [0., 0.]]), 6)

In [168]:
b=np.ones((2,2))
b.size,b

(4, array([[1., 1.],
        [1., 1.]]))

In [169]:
v=np.concatenate((a,b),axis=0)
v.size,v

(10, array([[0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.]]))

### 9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [170]:
a=np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [178]:
A=a.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [179]:
At=np.transpose(A)
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [186]:
B=A.dot(At)
B,B.shape

(array([[  5,  14,  23,  32],
        [ 14,  50,  86, 122],
        [ 23,  86, 149, 212],
        [ 32, 122, 212, 302]]), (4, 4))

In [189]:
det=np.linalg.det(B)
det

0.0

In [191]:
#B_inv = np.linalg.inv(B)

#### B квадратная матрица, но определитель=0  => обратной матрицы не существует

### 10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [205]:
np.random.seed(42)
np.random.permutation(10)


array([8, 1, 5, 0, 7, 2, 9, 4, 3, 6])

### 11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [208]:
c=np.random.randint(0,16,(16))
c

array([ 1, 15, 11,  4,  0, 11,  9,  5, 12, 11,  8,  0, 10, 10, 14,  9])

### 12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [212]:
C=c.reshape(4,4)
C    

array([[ 1, 15, 11,  4],
       [ 0, 11,  9,  5],
       [12, 11,  8,  0],
       [10, 10, 14,  9]])

In [213]:
D=(10*C)+B
D

array([[ 15, 164, 133,  72],
       [ 14, 160, 176, 172],
       [143, 196, 229, 212],
       [132, 222, 352, 392]])

In [214]:
det_D=np.linalg.det(D)
det_D

-55772400.00000009

In [216]:
rank_D=np.linalg.matrix_rank(D)
rank_D

4

In [248]:
D_inv=np.linalg.inv(D)
D_inv

array([[-0.00549304, -0.00302013,  0.01140277, -0.00383272],
       [-0.02277255,  0.03691145,  0.0196972 , -0.02266569],
       [ 0.05494546, -0.06695713, -0.03397021,  0.03765877],
       [-0.03459238,  0.04023782,  0.0155091 , -0.01713823]])

### 3. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [255]:
D_inv[D_inv>0] =1 
D_inv[D_inv<0]=0
D_inv

array([[0., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.]])

In [269]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [270]:
C

array([[ 1, 15, 11,  4],
       [ 0, 11,  9,  5],
       [12, 11,  8,  0],
       [10, 10, 14,  9]])

In [283]:
E=np.where(D_inv==1,B,C)
E

array([[  1,  15,  23,   4],
       [  0,  50,  86,   5],
       [ 23,  11,   8, 212],
       [ 10, 122, 212,   9]])

In [284]:
E.shape

(4, 4)