### Задание 1

In [63]:
import numpy as np

In [64]:
ar=np.array([[1, 2, 3, 3, 1],[6, 8, 11, 10, 7]])

In [65]:
a=np.transpose(ar)
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [67]:
mean_a=a.mean(0)
mean_a

array([2. , 8.4])

### Задание 2

In [69]:
a_centered=a-mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [70]:
### Задание 3

In [82]:
a_centered_sp=np.dot(a_centered[:,0],a_centered[:,1])
a_centered_sp

8.0

In [84]:
kov=a_centered_sp/(len(a)-1)
kov

2.0

In [85]:
### Задание 4

In [90]:
np.cov(np.transpose(a))


array([[1. , 2. ],
       [2. , 4.3]])